pub mod value;
pub mod heap;
pub mod gc;
pub mod entity;
pub mod frame;
pub mod task;
pub mod host;
pub mod error;
pub mod domain;
pub mod loader;
pub(crate) mod dispatch;
pub mod scheduler;
pub mod runtime;
pub mod virtual_module;

pub use value::{Value, HeapRef, GenHandle, TaskId, EntityId};
pub use heap::BumpHeap;
pub use gc::{GcHeap, GcStats, GcMode};
pub use entity::{EntityRegistry, EntitySlot, EntityState, PendingEntity};
pub use frame::CallFrame;
pub use task::{Task, TaskState};
pub use host::{RuntimeHost, HostRequest, HostResponse, NullHost, RequestId, LogLevel};
pub use error::{RuntimeError, CrashInfo, HostError};
pub use domain::{Domain, ResolvedRefs, ResolvedType, ResolvedMethod, ResolvedField};
pub use loader::LoadedModule;
pub use runtime::{Runtime, RuntimeBuilder, ExecutionLimit, TickResult, PendingRequest};
